services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ~/Individual-Graduation-Project/backend/ai_models/audio2text/whisper-large-v3:/app/ai_models/audio2text/whisper-large-v3
      - ~/Individual-Graduation-Project/backend/ai_models/text2text_summary/bert-large-uncased:/app/ai_models/text2text_summary/bert-large-uncased
      - ~/Individual-Graduation-Project/backend/.env:/app/.env
      # - /I/Vex/Proga/Individual-Graduation-Project/backend/ai_models/audio2text/whisper-large-v3:/app/ai_models/audio2text/whisper-large-v3
      # - /I/Vex/Proga/Individual-Graduation-Project/backend/ai_models/text2text_summary/bert-large-uncased:/app/ai_models/text2text_summary/bert-large-uncased
    networks:
      - app-network
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [ gpu ]
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=0

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
